T-128 Add contact us requests to the db
Sportresurs/sportresurs pull request #102
Opened 2021-09-28 17:45 UTC by Andrii-25

2021-09-28 17:46 UTC, Andrii-25 commented
@steven-tailor @Dimirolz не впевнений чи це я правильно робив.

2021-09-28 19:17 UTC, Dimirolz requested changes

2021-09-28 19:17 UTC, Dimirolz commented on migrations/20210928135421-create-request.js
> +      date: {
@Andrii-25 мне кажется это поле дублирует поле created_at

2021-09-28 19:17 UTC, Dimirolz commented on migrations/20210928135421-create-request.js
> +      tel: {
@Andrii-25 кажется `phone `привычней

2021-09-28 19:17 UTC, Dimirolz commented on migrations/20210928135421-create-request.js
> +      admin: {
@Andrii-25 `admin` должен хранить id из таблицы юзеров. Посмотри как в других миграциях создавали, там что то вроде

```js
taken_by: {
        type: Sequelize.INTEGER,
        references: {
          model: {
            tableName: "users",
          },
          key: "id",
        },
      },
 ```
 должно быть

2021-09-28 19:17 UTC, Dimirolz commented on migrations/20210928135421-create-request.js
> +      info: {
@Andrii-25 можно переименовать в `details`, как оно на фронте сейчас названо. 
Влад потом для своей таблицы с данными поменяет поля как ему нужно будет. Но в бд лучше более понятное названия использовать

2021-09-28 19:17 UTC, Dimirolz commented on pages/api/request.js
> +      const { date, status, admin, name, tel, info } = req.body;
@Andrii-25 мы не получаем админа, статус и дату с формы обратной связи. Это уже потом присваивается, но форма нам этого не пришлет

2021-09-28 19:17 UTC, Dimirolz commented on pages/api/request.js
> +  .get(async (req, res) => {
@Andrii-25 в целом метод get по идеи лежит уже в скоупе задач Сергея и Влада, как и обновление статуса у этих записей. Они тут должны будут сджоинить таблицу юзеров, что бы получить данные про админа, который последним менял запрос в таблице запросов.

2021-09-28 19:17 UTC, Dimirolz commented on pages/api/request.js
> +import Request from "../../models/request";
@Andrii-25 тут есть нюанс, по крайней мере мы так с Сергеем начали уже делать.
Там в папке models есть index.js, в который мы добавляем все модели, а потом уже оттуда их берем в апи роуты.
Типо `import { Request } from "../../models";`

2021-09-29 09:06 UTC, Andrii-25 commented on pages/api/request.js
> +  .get(async (req, res) => {
@Dimirolz я так розумію можу забрати свій метод get?

2021-09-29 16:39 UTC, Dimirolz requested changes

2021-09-29 16:39 UTC, Dimirolz commented on pages/api/request.js
> +    res.json(newRequest);
@Andrii-25 можно объединить в 1 строку. `res.status(201).json(newRequest)`

2021-09-29 16:39 UTC, Dimirolz commented on pages/api/request.js
> +    res.json(err);
@Andrii-25 в случае если этот код упадет, думаю было бы неплохо узнать об этом в Sentry. Ты можешь добавить тут вызов `captureException(err)`, такой метод есть у либы sentry, не забудь за импорт

2021-09-29 16:39 UTC, Dimirolz commented on models/request.js
>    class Request extends Model {}
@Andrii-25 в дальнейшем ребятам понадобится получать админа, который у нас хранится как id. Ты можешь уже сейчас добавить hasOne association с таблицей users.
Не совсем в этом уверен, так что лучше проверь как оно будет работать в sequelize.

2021-09-30 13:12 UTC, Dimirolz commented
@steven-tailor по моим правкам Андрей все сделал, можешь посмотреть как будет время?

2021-09-30 13:35 UTC, steven-tailor approved these changes

2021-09-30 13:40 UTC, Dimirolz approved these changes

2021-09-30 13:40 UTC, merged