t-98-implement desctop pin functionality
Sportresurs/sportresurs pull request #103
Opened 2021-09-29 07:19 UTC by Dr-Frame

2021-10-01 08:56 UTC, WebTarantul requested changes
In general looks good, but I found some moments to fix it.

2021-10-01 08:56 UTC, WebTarantul commented on pages/map.js
> +  const [markerIndex, setMarkerIndex] = useState(0);
If sidebar is closed changing of current pin does't opens sidebar

2021-10-01 08:56 UTC, WebTarantul commented on components/MapMarkerWrapper/MapMarkerWrapper.js
> +      onClick={() => setMarkerIndex(id)}
![image](https://user-images.githubusercontent.com/34688235/135589439-b54774db-2082-4bde-aa9f-be811311e838.png)

2021-10-01 08:56 UTC, WebTarantul commented on pages/map.js
>    const [filteredPlaces, setFilteredPlaces] = useState([]);
useEffect on line 24 is not used. Please remove it

2021-10-01 08:56 UTC, WebTarantul commented on components/MapMarkerWrapper/MapMarkerWrapper.js
> +  const id = indexMarker;
Index is not id

2021-10-01 08:56 UTC, WebTarantul commented on components/PlaygroundItem/PlaygroundItem.jsx
> +  if (isActive && screenWidth > 950) {
This is a some effect then please move that block into useEffect hook with needed depedendsies

2021-10-01 08:56 UTC, WebTarantul commented on components/PlaygroundsList/PlaygroundsList.jsx
> +          <li ref={elRefs[i]} className={styles.listItem} key={playground.id}>
That way is possible but more clearly if you use forwarding refs(if you want)

https://ru.reactjs.org/docs/forwarding-refs.html

2021-10-04 08:10 UTC, Dr-Frame commented on pages/map.js
> +  const [markerIndex, setMarkerIndex] = useState(0);
I don't fully understand what exactly do you mean

2021-10-06 07:49 UTC, WebTarantul approved these changes

2021-10-06 08:11 UTC, Dimirolz commented
@Dr-Frame пофикси конфликты, что бы я смог смерджить

2021-10-06 08:54 UTC, merged