T 111 create add a court admin modal
Sportresurs/sportresurs pull request #107
Opened 2021-10-01 14:03 UTC by artemSr

2021-10-01 18:44 UTC, ZakharovMaxim requested changes

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/Select/Select.js
> +  labelSize,
Не вижу propTypes для labelSize и прочих пропсов.

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/Select/Select.js
> +import React, { useState } from "react";
Импорт React?

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/MultiSelect/MultiSelect.module.scss
> +  margin-bottom: 12px;
Лучше не ограничивать ширину в самом компоненте. Тоже самое касается margin, это то как компонент взаимодействует с другими компонентами, лучше сделать это в в компоненте, который использует данный компонент

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/MultiSelect/MultiSelect.module.scss
> +  .filterType {
Почему не создать отдельный класс для этого вместо вложенности?

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/Input/Input.module.scss
> +  max-width: 492px;
Я так понимаю это сделано из-за того, что у инпута уже есть другое значение max-width? Я бы убрал max-width из этого компонента, сделал width: 100%; а max-width пусть будет у родительского компонента, например у формы.

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/Input/Input.jsx
> +  errorStyle,
Если используем настолько специфические пропсы, то хотя бы нужно добавить propTypes

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/Filters/FilterWindow.jsx
> +          onChange={setDistricts}
onChange в конец пропсов, касается всех полей

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.module.scss
> +  left: 40%;
Если это попытка разместить по центру, то нужно использовать 50% и transform

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +            {new Array(3).fill(1).map((_, index) => (
3 лучше вынеси в константу, чтобы понимать, что это за число такое

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +                        {(provided) => (
Почему бы не применить сразу деструктуризацию и взять только нужны поля? Тогда можно убрать eslint комментарий

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +                {(provided) => (
Можно применить деструктуризацию

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +    const file = reorder(files, result.source.index, result.destination.index);
file? только один?

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +        [].concat(
Если мы используем деструктуризацию внизу, то почему бы не применить ее и тут?

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/CustomValidationSchema.js
> +import * as Yup from "yup";
Этому файлу не место в components, лучше вынести в отдельную папку

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +    Object.keys(values).map((item) => {
Eslint не зря ругается, map возвращает новый массив, если ты этого не хочешь, то используй forEach. В Object.keys будут ключи, поэтому item лучше переименовать в key

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +      formData.append(`${item}`, value);
Оборачивать в шаблонные строки не обязательно

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +      files.map((file) => file.file)
Лучше применить деструктуризацию, ({file}) => file

2021-10-01 18:44 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +];
Это данные мы используем и в других местах приложения, нет более подходящего места где их можно разместить?

2021-10-02 07:23 UTC, artemSr commented on components/CustomDropzone/CustomDropzone.module.scss
> +  left: 40%;
из-за padding-top у imageContainer такой способ не работает

2021-10-02 07:45 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.module.scss
> +  left: 40%;
> из-за padding-top у imageContainer такой способ не работает

Не вижу причин этому способу не работать
![image](https://user-images.githubusercontent.com/24988948/135708195-92ada349-0a10-4910-b733-eaf44c8155af.png)

2021-10-04 08:12 UTC, ZakharovMaxim requested changes

2021-10-04 08:12 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +const DEFAULT_IMAGES = 3;
DEFAULT_IMAGES -> DEFAULT_IMAGES_LENGTH

2021-10-04 08:12 UTC, ZakharovMaxim commented on components/CustomValidationSchema/CustomValidationSchema.js
> +import * as Yup from "yup";
В компонентах лежат компоненты, для этого файла нужна другая папка рядом с components

2021-10-04 08:12 UTC, ZakharovMaxim commented on components/Input/Input.jsx
> +  inputSize: PropTypes.string,
Я думаю у этих полей есть определенный набор допустимых значений, если я передам любую строку в этом не будет особого смысла

2021-10-04 08:12 UTC, ZakharovMaxim commented on components/Select/Select.js
> +  labelSize: PropTypes.string,
labelSize принимает набор определенных значений

2021-10-04 08:12 UTC, ZakharovMaxim commented on utils/testData/AddCourtFormOptions.js
> +];
Разве этих значений нет в testData/testArrs.js?

2021-10-04 10:26 UTC, ZakharovMaxim requested changes

2021-10-04 10:26 UTC, ZakharovMaxim commented on components/Input/Input.jsx
> +  errorStyle: PropTypes.oneOf(["formErrorIcon"]),
Нужно расширить валидацию

2021-10-04 10:26 UTC, ZakharovMaxim commented on validationSchema/index.js
> +export { default } from "./CustomValidationSchema";
Схем для валидации может быть несколько, не нужно под каждую создавать отдельную папку, можно создать папку validationSchemas и там размесить все схемы, index.js можно создать, но не для дефолтного экспорта каждой схемы, а чтобы мы могли испортировать схему прям из этой папки через named export, e.g import { CreatePlaygroundValidationSchema } from './validationSchemas'

2021-10-04 10:26 UTC, ZakharovMaxim commented on utils/testData/testArrs.js
> +  { label: "Спортивний", value: "Спортивний" },
Данные по прежнему дублируются

2021-10-04 10:26 UTC, ZakharovMaxim commented on components/CustomDropzone/CustomDropzone.jsx
> +        [...currentFiles, ...acceptedFiles].map((file) => {
map только для acceptedFiles

2021-10-05 09:55 UTC, ZakharovMaxim commented on pages/home/Home.js
> -
Не совсем понял этого изменения, и разве Home.js не должен быть в pages/index?

2021-10-05 09:55 UTC, ZakharovMaxim commented on pages/index.js
> +  const [modal, setModal] = useState(false);
Еще нет хука?

2021-10-05 10:58 UTC, ZakharovMaxim approved these changes

2021-10-05 11:29 UTC, Dimirolz approved these changes

2021-10-05 11:29 UTC, merged