T-123 Fetch playgrounds from DB
Sportresurs/sportresurs pull request #116
Opened 2021-10-06 16:03 UTC by Dr-Frame

2021-10-08 10:44 UTC, WebTarantul requested changes

2021-10-08 10:44 UTC, WebTarantul commented on pages/map.js
> +  const [places] = useState(playgrounds);
You don't need to set playgrounds into state, because you can work with source data(playgrounds) instead.
One more moment. If the playgrounds change the places does not change.

2021-10-08 10:44 UTC, WebTarantul commented on pages/map.js
> +  const res = await fetch(process.env.PLAUGROUNDS_HOST);
Don't use a env variable for specific endpoint. You can use HOST as env variable. E.g. `fetch(${process.env.HOST/playgrounds})`

2021-10-08 10:44 UTC, WebTarantul commented on pages/playgrounds/index.js
> +  const res = await fetch("http://localhost:3000/api/areas");
Please use some .env variable for host

2021-10-08 15:43 UTC, Dimirolz commented on pages/map.js
> +  const res = await fetch(process.env.PLAUGROUNDS_HOST);
@WebTarantul why not to use relative path for this? Is this a bad way?

2021-10-11 05:40 UTC, Dr-Frame commented on pages/home/index.js
> +
I have found that this is the small problem in SearchSection where we put <Button/> component inside <Link>. But as far as I know Button component has prop which is define wether it should be <button/> or <a/> tag, but probably it's not working as intended. I told it to Bogdan and he will replace the <Button/> component with a <a/> tag. 
I just fixed a part with proptypes

2021-10-11 06:50 UTC, WebTarantul commented on pages/map.js
> +  const res = await fetch(process.env.PLAUGROUNDS_HOST);
@Dimirolz @Dr-Frame Of course, this is a very bad way. Variables env. cannot depend on a directory tree or file tree.

2021-10-11 07:22 UTC, WebTarantul approved these changes

2021-10-11 08:19 UTC, merged