Dev 35 implement header
Sportresurs/sportresurs pull request #12
Opened 2021-08-27 11:54 UTC by Bohdan-R

2021-08-30 08:19 UTC, WebTarantul commented on components/Header/Header.module.scss
> +    width: 1440px;
There no reasons to use width property. Please use max-width instead, because we want make a responsive layout.

2021-08-30 08:19 UTC, WebTarantul commented on components/Header/Header.module.scss
> +
![image](https://user-images.githubusercontent.com/34688235/131308448-815e5ced-6532-445c-b427-6c53b17c1040.png)

2021-08-30 17:17 UTC, WebTarantul commented on components/Header/Header.module.scss
> +
![image](https://user-images.githubusercontent.com/34688235/131372127-fedb04a9-ae7e-44fc-891e-b6fb58c7c0e0.png)
![image](https://user-images.githubusercontent.com/34688235/131378296-87f3682a-adea-4782-ae51-57d9399b937d.png)

2021-08-31 07:00 UTC, WebTarantul commented on components/Header/Header.js
> +  const menuOpen = `${styles.backdrop} ${styles.isOpen}`;
Please read the documentation. That's library give you ability to write code like this:
`
import cn from "classnames/bind";
import s from "./Header.module.scss";
const cx = cn.bind(s);

//inside the component
  <div
    className={cx("backdrop", { isOpen: menuActive })} 
  />
`

2021-08-31 07:11 UTC, WebTarantul commented on components/Header/Header.module.scss
> +    padding-left: 50px;
In the design padding left is 30px

2021-08-31 07:11 UTC, WebTarantul commented on components/Header/Header.js
> +  const combineClassName = className(s.backdrop, s.isOpen);
Please, read the documentation. That's library give you ability to write code like this:
`
import cn from "classnames/bind";
import s from "./Header.module.scss";
const cx = cn.bind(s);

then:
<div
      className={cx("backdrop", { isOpen: menuActive })}
   />
`

2021-08-31 09:36 UTC, WebTarantul requested changes

2021-08-31 09:36 UTC, WebTarantul commented on components/Header/Header.js
> +  const cx = classNames.bind(s);
binding inside the component is not best path

2021-08-31 15:31 UTC, WebTarantul approved these changes

2021-08-31 17:11 UTC, Dimirolz commented
@Bohdan-R нужно исправить конфликтующие файлы, что бы я смог смерджить эту ветку в develop.

2021-09-01 07:29 UTC, merged