t-133 implement the back end for playground modal window
Sportresurs/sportresurs pull request #127
Opened 2021-10-13 12:42 UTC by artemSr

2021-10-13 13:00 UTC, Dimirolz commented on models/request.js
> +    // }
@artemSr а для чего это было закоментировано тут?

2021-10-13 14:09 UTC, Dimirolz commented on package.json
> +    "busboy": "^0.3.1",
@artemSr лишняя зависимость

2021-10-13 16:16 UTC, ZakharovMaxim requested changes

2021-10-13 16:16 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +      await axios({
Это нужно заменить на вызов метода сервиса, к тому же мы создали конфиг для axios-а, нет нужны каждый раз писать полностью название хоста.

2021-10-13 16:16 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +          <>
Можем вынести это в отдельный компонент? e.g. 
```
<WithLoader isLoading={isInitialDataLoading}>
<h1 className={styles.heading}
...
</WithLoader>
```

2021-10-13 16:16 UTC, ZakharovMaxim commented on middleware/formDataConvert.js
> +    req.images = file;
Вместо images лучше files, file -> files

2021-10-13 16:16 UTC, ZakharovMaxim commented on pages/home/Home.js
> +import styles from "./Home.module.scss";
Стили лучше импортировать после компонентов

2021-10-13 16:16 UTC, ZakharovMaxim commented on api/playgroundService.js
> +import instance from "./instance";
лучше переименовать instance в axios, потому что не ясно, instance чего это.

2021-10-13 16:16 UTC, ZakharovMaxim commented on pages/api/playground.js
> +      const purposeArray = purpose.split(",");
А почему purpose приходит как строка вместо массива?

2021-10-14 14:02 UTC, ZakharovMaxim commented on middleware/formDataConvert.js
> +  await form.parse(req, (err, fields, files) => {
Зачем await, если мы обрабатываем результат в колбеке?

2021-10-14 14:04 UTC, ZakharovMaxim commented on pages/home/index.js
> +        <AdminPlaygroundModal visible={true} />
Я не думаю, что эта модалка нам нужна на главной странице сейчас, ее можно сразу интегрировать с кнопкой и показывать только для админка, либо пока что просто спрятать

2021-10-14 14:04 UTC, ZakharovMaxim commented on utils/hooks/useAsyncData.js
> +        const resData = await method();
Мне кажется эта переменная лишняя

2021-10-14 14:06 UTC, ZakharovMaxim commented on pages/api/playground.js
> +      const imgData = req.files.images;
imgData название как-будто у нас данные об одном изображении, лучше заменить на images

2021-10-14 14:07 UTC, ZakharovMaxim commented on pages/api/playground.js
> +      });
Можно заменить на метод map

2021-10-14 14:08 UTC, ZakharovMaxim commented on pages/api/playground.js
> +import compressImg from "../../utils/imageCompression/compress";
Я думаю не стоит экономить эти 2 символа и написать image полностью

2021-10-14 14:09 UTC, ZakharovMaxim commented on pages/api/playground.js
> +        blobImages.map(async (img) => compressImg(img))
Не вижу смысла от async, если нигде нет await

2021-10-14 14:18 UTC, ZakharovMaxim commented on pages/api/playground.js
> +        blobImages.push(fs.readFileSync(img.path));
Я бы вынес это в отдельный метод, сделал бы его асинхронным и использовал бы readFile вместо readFileSync.
`const fs = require('fs').promises
function filesToBlobs (files) {
const readFilePromises = files.map(file => fs.readFile(file.path))
return Promise.all(readFilePromises).then(...)
}` Остается только обработать результат

2021-10-14 14:21 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +  };
Не вижу смысла в этих условиях, если мы все равно устанавливаем одно и тоже значение

2021-10-14 14:22 UTC, ZakharovMaxim commented on components/AdminPlaygroundModalContent/AdminPlaygroundModalContent.jsx
> +                    </div>
Это нужно вынести в отдельный компонент

2021-10-14 16:32 UTC, ZakharovMaxim commented on components/TimeInput/TimeInput.jsx
> +      <p className={styles.timeLabel}>часи роботи</p>
label нужно передавать через props

2021-10-14 16:34 UTC, ZakharovMaxim commented on api/playgroundService.js
> +  getPurpose() {
getPurposes

2021-10-14 16:58 UTC, ZakharovMaxim approved these changes

2021-10-15 07:58 UTC, Dimirolz approved these changes

2021-10-15 07:58 UTC, merged