Eslint prettier setup
Sportresurs/sportresurs pull request #14
Opened 2021-08-30 08:26 UTC by Dimirolz

2021-08-30 08:28 UTC, Dimirolz commented
@steven-tailor читал про .prettierrc, но не создавал. Вроде бы заработало без него. Если он нужен, то что в нем нужно писать?

2021-08-30 08:38 UTC, Dimirolz commented
Добавил husky с pre-commit хуком, который будет линтить перед коммитом. В эту ветку было норм такое делать? Или нужно было отдельную создавать?

2021-08-30 10:15 UTC, epaminond commented on .eslintrc.json
> +    "no-console": "off",
Я бы проверял это, а отключал в конкретных `// eslint-disable-line`
Иначе куча дебаг-инфы попадает потом в прод.

2021-08-30 10:19 UTC, WebTarantul commented on .eslintrc.json
> +    "no-console": "off",
можна додати плагін eslint import order

2021-08-30 10:25 UTC, steven-tailor commented
> @steven-tailor читал про .prettierrc, но не создавал. Вроде бы заработало без него. Если он нужен, то что в нем нужно писать?

Укажи для начала базовый конфиг
`trailingComma: "all"
tabWidth: 2
semi: true
singleQuote: true
printWidth:  80`

Значения дефолтные, но всегда лучше указать явно. С printWidth можете решить вместе какая ширина будет удобна

2021-08-30 11:48 UTC, Dimirolz commented
> 
> 
> > @steven-tailor читал про .prettierrc, но не создавал. Вроде бы заработало без него. Если он нужен, то что в нем нужно писать?
> 
> Укажи для начала базовый конфиг
> `trailingComma: "all" tabWidth: 2 semi: true singleQuote: true printWidth: 80`
> 
> Значения дефолтные, но всегда лучше указать явно. С printWidth можете решить вместе какая ширина будет удобна

Посмотрел в документацию prettier, вроде бы singleQuote стоит по default false. Может не туда глянул, но мне показалось что и сейчас prettier заменяет на двойные кавычки. Все равно ставим singleQuote: true?

p.s. @steven-tailor почему то не могу ответить прямо под комментарием, не знаю почему

2021-08-30 11:49 UTC, Dimirolz commented on .eslintrc.json
> +    "no-console": "off",
@epaminond речь про все правила в этом блоке? Или про конкретно те 3 выделенных? Мне казалось что prettier/prettier обязательно должен бьыть error, иначе во время линтинга не падает ошибка.

2021-08-30 11:53 UTC, Dimirolz commented on .eslintrc.json
> +    "plugin:import/recommended",
@WebTarantul добавил eslint-plugin-import. Но не уверен что правильно. Возможно для него нужны еще какие то настройки?

2021-08-30 13:27 UTC, epaminond commented on .eslintrc.json
> +    "no-console": "off",
Я про `no-console`. )

2021-08-30 15:07 UTC, Dimirolz commented on .eslintrc.json
> +    "no-console": "off",
@epaminond включил и поменял на error. Правильно понял, что использовать console log мы можем, но только что бы локально проверять. Но CI и pre-commit хук упадут, если мы попытаемся такое запушить?

2021-08-30 15:13 UTC, epaminond commented on .eslintrc.json
> +    "no-console": "off",
По логике да.
Но если где-то всё же нужно оставить `console.log` - то явно можно это указать через `// eslint-disable-line`.

2021-08-30 16:22 UTC, IgVol requested changes

2021-08-30 16:22 UTC, IgVol commented on .eslintrc.json
> +    "object-shorthand": "off",
зачем нужны
"object-shorthand": "off",
"class-methods-use-this": "off"
"no-process-exit": "off"?
сюда error, ненужные переменные ухудшают качество кода
"no-unused-vars": "warn",

2021-08-30 16:29 UTC, Dimirolz commented on .eslintrc.json
> +    "object-shorthand": "off",
@IgVol честно говоря не знаю. Следовал гайду и оно заработало.
Сейчас тогда уберу. И unused поставлю error

2021-08-30 16:36 UTC, Dimirolz commented on .eslintrc.json
> +  "plugins": ["prettier"],
Про prettier/react спросил выше.
Вопрос по jsx-a11y, после установки у меня выпали вот такие ошибки.
![изображение](https://user-images.githubusercontent.com/23504324/131373295-d5031266-16a7-4594-b292-b60dc7202033.png)
Как их правильно пофиксить?)

2021-08-30 18:50 UTC, IgVol commented on .eslintrc.json
> +  "plugins": ["prettier"],
no-static-element-interaction и no-noninteractive-element-interactions Дивы и спаны не должны быть кликабельны
click-events-key-events можно отключить

2021-08-30 19:00 UTC, IgVol commented on .eslintrc.json
> +  "plugins": ["prettier"],
@Dimirolz переключи в режим warning

2021-08-30 19:16 UTC, Dimirolz commented on .eslintrc.json
> +  "plugins": ["prettier"],
@IgVol переключил и все вместе закоммитил

2021-08-30 20:09 UTC, IgVol approved these changes

2021-08-31 06:29 UTC, steven-tailor commented
> > > @steven-tailor читал про .prettierrc, но не создавал. Вроде бы заработало без него. Если он нужен, то что в нем нужно писать?
> > 
> > 
> > Укажи для начала базовый конфиг
> > `trailingComma: "all" tabWidth: 2 semi: true singleQuote: true printWidth: 80`
> > Значения дефолтные, но всегда лучше указать явно. С printWidth можете решить вместе какая ширина будет удобна
> 
> Посмотрел в документацию prettier, вроде бы singleQuote стоит по default false. Может не туда глянул, но мне показалось что и сейчас prettier заменяет на двойные кавычки. Все равно ставим singleQuote: true?
> 
> p.s. @steven-tailor почему то не могу ответить прямо под комментарием, не знаю почему

С кавычками - дело предпочтения. Мне привычнее `singleQoute: true`.

2021-08-31 07:20 UTC, merged