Dev 43/image compression
Sportresurs/sportresurs pull request #17
Opened 2021-08-30 19:40 UTC by Andrii-25

Created images compression function.

2021-08-30 19:44 UTC, Dimirolz commented
@Andrii-25 Привет, не переживай, CI упал не по твоей вине, это из за dotenv-safe, в самом CI не установлены те переменные окружения что есть у тебя в .env.example, завтра обсужу это с @epaminond и придумаем что делать в таких случаях

2021-08-30 21:47 UTC, epaminond commented
Тут есть совет использовать разные example для CI: https://github.com/rolodato/dotenv-safe#continuous-integration-ci

Кстати, allowEmptyValues в true отключает ошибку?

2021-08-31 06:29 UTC, Dimirolz commented
@epaminond не отключает, попробовал локально. Переменная должна быть хотя бы задана, но с allowEmptyValues она может быть пустой. Но в CI она совсем не задана сейчас.

Мне кажется конкретно в этой задаче можно обойтись без env переменных, но еще уточню у Андрея, вдруг на то были причины.

2021-08-31 07:01 UTC, Dimirolz commented on utils/convert.js
> +function convertImgToBuffer(image) {
@Andrii-25 мне кажется можно укоротить название на `convertImg` или `prepareImg`, или `transformImg`. Префикс ToBuffer мне кажется излишним, так как image изначально уже и есть Buffer тип.

2021-08-31 08:34 UTC, epaminond commented on utils/convert.js
> +} = process.env;
Я бы не усложнял до момента, когда это потребуется. )

2021-08-31 09:22 UTC, Andrii-25 commented on utils/convert.js
> +} = process.env;
Привіт, тоді я поки що їх заберу з env.

2021-08-31 09:45 UTC, Dimirolz commented on utils/convert.js
> +} = process.env;
@epaminond Не совсем тут понял)
В каком направлении не усложняем?) 
Делаем конфиг или оставляем .env, но добавляем переменные в heroku и в ci?

2021-08-31 09:47 UTC, epaminond commented on utils/convert.js
> +} = process.env;
Можно вообще в константы забить, пока не потребуются настройки. )

2021-08-31 09:51 UTC, steven-tailor commented on utils/convert.js
> +function convertImgToBuffer(image) {
@Dimirolz это не так, результатом выполнения может быть сохранение картинки в файловой системе. Так что в этом случае уточнение важно.

2021-08-31 09:58 UTC, steven-tailor commented on utils/convert.js
> +} = process.env;
Предлагаю все таки поставить `convict` как компромиссное решение. Потому как чем дальше тем больше будет подобных проблем. И с конвертацией нам нужно будет подбирать оптимальные конфиги.

2021-08-31 10:06 UTC, steven-tailor commented on utils/convert.js
> +function convertImgToBuffer(image) {
Думаю тут больше проблема в том что мы говорим о конвертации хотя на самом деле занимаемся компрессией

2021-09-01 07:48 UTC, Dimirolz commented on utils/convert.js
> +function convertImgToBuffer(image) {
@steven-tailor субъективно, но если функция и конвертит и на диск сохраняет, то возможно лучше ее разделить на две функции. Одна конвертит, вторая сохраняет Buffer на диск, в бд, на s3 или куда то. Так бы мы разделили их ответственности, мне кажется

Тут происходит и компрессия и конвертация в другой формат, может вариант с `prepareImg` описывал бы оба эти процесса.

2021-09-02 06:04 UTC, steven-tailor commented on utils/convert.js
> +function convertImgToBuffer(image) {
@Dimirolz В этом случае он возвращает только `Buffer`. 

Это правда - нейминг дело философское. Но все же я склоняюсь к тому что чем подробнее названы переменные тем проще читать код. Тенденция на упрощение названий уместна если код и так хорошо описан например через `JsDoc` или типизирован. Тогда у нас есть больше источников и есть на что ориентироваться.

Но опять же ты как TL можешь установить правила нейминга (`operation + entity + response` или `entyty + operation`) тогда будет выручать единственность логики.

2021-09-02 09:21 UTC, epaminond commented on utils/convert.js
> +    })
Why not using shorthands like this:

```
//...
.jpeg({ quality, chromaSubsampling })
```

Relevant to a few other places within PR

2021-09-06 16:53 UTC, Dimirolz commented
@steven-tailor @epaminond что в итоге решаем по этой задаче?

2021-09-07 07:19 UTC, epaminond approved these changes

2021-09-07 07:21 UTC, epaminond commented
Тут конфликты надо пофиксить.
В общем выглядит норм.
Минус: нет примера использования, но если задача по созданию ендпоинта для загрузки фоток тоже на @Andrii-25  - то это не проблема.

2021-09-07 07:27 UTC, steven-tailor requested changes

2021-09-07 07:27 UTC, steven-tailor commented on utils/compress.config.js
> +    default: 1200,
тут стоит указать название переменной среды что бы можно было менять конфиги как мы и говорили. Тоже касается и imageHeight, imageQuality

2021-09-08 13:42 UTC, Andrii-25 commented on utils/compress.config.js
> +    default: 1200,
@steven-tailor тут я не до кінця зрозумів

2021-09-09 12:20 UTC, steven-tailor commented on utils/compress.config.js
> +    default: 1200,
@Andrii-25 добавь в конфиги выше (imageHeight, imageQuality, imageWidth) свойство `env` со стринговым значением, хранящим название переменной среды. Например:
`imageWidth: {
   ...,
   env: 'PLAYGROUND_IMAGE_WIDTH',
}
`

2021-09-13 09:53 UTC, epaminond commented
Тут дальше конфликты

2021-09-13 09:54 UTC, steven-tailor approved these changes

2021-09-13 09:55 UTC, Dimirolz commented
@Andrii-25 пофикси конфликты, что бы я смог смерджить

2021-09-13 18:40 UTC, Dimirolz commented
@Andrii-25 мне кажется последний коммит что то не то сделал. Там должны было быть только несколько файлов, которые конфликтовали.

@steven-tailor что в таком случае лучше делать? Я пока сам не до конца понимаю ситуацию

2021-09-14 19:37 UTC, steven-tailor commented
@Dimirolz @Andrii-25 всем кто юзал ветку нужно её локально дропнуть и спулить заново (я переписал историю).

2021-09-15 06:01 UTC, merged