Implement the contact us modal window layout,fix modal component styles, add Textarea component
Sportresurs/sportresurs pull request #43
Opened 2021-09-07 12:39 UTC by artemSr

…es, add Textarea component

2021-09-07 13:55 UTC, ZakharovMaxim requested changes

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModal/ContactUsModal.jsx
> +  visible: PropTypes.bool,
onClose prop?

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +          alert(JSON.stringify(values, null, 2));
Можно добавить имитацию асинхронной отправки формы, а после отправки закрыть модалку

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +        validationSchema={Yup.object({
Это нужно вынести в отдельный модуль.

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +            "Колличество символов не должно превышать 200"
Количество*

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              {...formik.getFieldProps("name")}
rest лучше писать в конце атрибутов

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              {...formik.getFieldProps("phone")}
В конец

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              id="details"
Зачем id?

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              id="phone"
Зачем id?

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +            {formik.errors.phone ? (
Вывод ошибок должен быть в компоненте Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +            {formik.errors.name ? (
Вывод ошибок должен быть в компоненте Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              id="name"
Зачем id?

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +            {formik.errors.details ? (
Вывод ошибок должен быть в компоненте Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  max-width: 356px;
Слишком много max-width, я бы дал всей модалке больше padding, и отдельный элементам, которые меньше чем сама форма, дал бы дополнительный padding справа, или заменил max-width с фиксированной шириной на проценты(зависит от адаптивного дизайна)

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  max-width: 322px;
Смотри комментарий для .form

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  padding: 71px 136px;
Смотри комментарий для .form

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  max-width: 262px;
Смотри комментарий для .form

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +.errorMsg {
Этот компонент должен быть в Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +.large {
Слишком много дублирования, должен быть базовый класс .modal и его модификации .large, .medium, .small, имеющие свойство max-width. По аналогии с кнопками

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .playground,.contact,.thanks {
Что это? Тут не должно быть ничего конкретного, это абстрактный компонент, он не знает про то, в каком контексте он используется

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .playground,.contact,.thanks {
Смотри комментарий выше

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .playground,.contact,.thanks {
Смотри комментарий выше

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .playground,.contact,.thanks {
Смотри комментарий выше

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/PlaygroundModal/PlaygroundModal.jsx
> +    variant="playground"
Нужно использовать другие значения для variant. Что мне говорит prop variant="playground"? Абсолютно ничего, Компонент модалки должен быть более абстрактным

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Textarea/Textarea.jsx
> +import React from "react";
Нужно обхединить с Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/Textarea/Textarea.module.scss
> +@import "styles/colors";
Нужно объединить с Input

2021-09-07 13:55 UTC, ZakharovMaxim commented on components/input/Input.jsx
>  import styles from "./Input.module.scss";
Раз уж мы начали править компонент Input, возможно стоит его расширить, чтобы он поддерживал textarea?

2021-09-07 13:56 UTC, ZakharovMaxim commented
Я бы делал не только компонент ContactUs, но делал бы компонент, который объединит кнопку "Свяжитесь с нами" и модалку. Посмотри в сторону https://ru.reactjs.org/docs/portals.html

2021-09-07 17:44 UTC, ZakharovMaxim requested changes

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsButton/ContactUsButton.jsx
> +      <Button variant={"lilac"} size={"medium-dense"} onClick={handleOpen}>
Фигурные скобки не обязательны тут.

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModal/ContactUsModal.jsx
> +    onClose={onClose}
Слушатели событий лучше писать после атрибутов.

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +import backgroundImg from "./images/basketball.png";
Мы бы могли использовать svg, к тому же, я думаю, что у нас уже должна быть эта картинка. И изображение лучше класть или в public или создать папку assets/images

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              label={formik.errors.phone ? <p>{formik.errors.phone}</p> : null}
Зачем в label передавать ошибку? Для ошибки должен быть отдельный prop. Дизайн систему обновили, теперь input отображает текст ошибки

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.jsx
> +  const variantClassName = classNames(styles.modal, styles[variant]);
Это не variantClassName, название переменной не соответствует тому, что она хранит, нужно подобрать другое название e.g. contentClassName

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              label={
Ошибка не должна идти в label

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  background: $color-primary-light;
Фон пусть задается в дочернем компоненте. Если хочется задавать цвет фона непосредственно в модалке, то нужно добавлять новый prop, делать это в prop, который отвечает за размер, не нужно.

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  background: $color-secondary-yellowish;
Смотри комментарий к .large

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  background: $color-secondary-yellowish;
Смотри комментарий к .large

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .large,.medium,.small {
зачем писать 3 варианта, если можно использовать базовый класс .modal?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .large,.medium,.small {
зачем писать 3 варианта, если можно использовать базовый класс .modal?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .large,.medium,.small {
зачем писать 3 варианта, если можно использовать базовый класс .modal?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +  .large,.medium,.small {
зачем писать 3 варианта, если можно использовать базовый класс .modal?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/PlaygroundModalContent/CustomFormik.jsx
> +import React from "react";
Я бы назвал этот компонент по-другому, CustomFormik не совсем понятное название, учитываю, что компонент выполняет вполне конкретное действие, для конкретной формы. Не совсем понимаю расположение компонента, что он делает в PlaygroundModalContent?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +        <div alt="" className={styles.errorIcon}>
alt?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +      {label && <label className={styles.inputLabel}>{label}</label>}
label должен быть там где label, тут должна быть ошибка

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.module.scss
> +.inputLabel {
label это label, это описание инпута, для ошибки должен быть отдельный класс

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +  size: ["small", "large"],
Мне кажется, что size становится large тогда и только тогда, когда as равен textarea

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +  size: PropTypes.oneOf(["small", "large"]).isRequired,
Не вижу особого смысла в этот пропсе

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.module.scss
> +.large {
Смотри комментарии про props

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +        className={wrapperClassName}
Не совсем понимаю, почему wrapperClassName, если он ничего не оборачивает? inputClassName подходит лучше

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/PlaygroundModalContent/CustomFormik.jsx
> +import React from "react";
И в целом, я не вижу особой выгоды от вынесения всего компонента, я предлагаю вынести только описание Yup схемы в отдельный файл, можно создать utils/schemas.js и так хранить описание наших форм(у нас их всего 2 будет). И нужно добавить асинхронную загрузку, создать сервис api/customerService.js, создать фейковый метод для отправки асинхронного запроса и в компоненте формы обработать асинхронный запрос, показать лоадер, а в конце закрыть форму.

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              label={formik.errors.name ? <p>{formik.errors.name}</p> : null}
Не путать ошибки и label

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  textarea {
Я думаю это правило не требуется, если мы начали менять Input

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +    margin-top: 18px;
Если нужно дать margin для инпутов то лучше их обернуть в .formGroup элемент

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  justify-content: center;
если кнопка имеет display: inline-block то достаточно одного text-align: center

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  margin: 36px 0 0;
Одного margin-top не достаточно?

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  top: 394px;
Так как изображение находится справа внизу, я бы использовал свойста right, bottom

2021-09-07 17:44 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +        Залиште свої контактні дані і ми вам зателфеонуємо
Опечатка

2021-09-08 09:42 UTC, ZakharovMaxim requested changes

2021-09-08 09:42 UTC, ZakharovMaxim commented on api/customerService.js
> +  const promise = new Promise((resolve) => {
Можно сразу возвращать промис, нет смысла выносить его в переменную. 5 секунд это слишком долго, достаточно 1-2 секунд

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +          onSubmit={async (values) => {
Лучше вынести в отдельный метод и нужно обработать ошибку

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +                  formik.touched.name && <p>{formik.errors.name}</p>
Зачем тег p? Не вижу смысла иметь 2 props-а isError, errorMsg, потому что они дублируют друг друга, достаточно errorMsg, который нужно переименовать в errorMessage. Сам процес получения ошибки из formik я бы вынес в helper метод, который будет принимать formik и название поля, тогда не нужно дублировать одну и ту же логику для 2 полей

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +                  {loading ? <Spiner /> : <p>Надіслати</p>}
Тут абзац лишний

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  input, textarea:nth-of-type(n){
зачем position: relative и zIndex? margin нужно дать самому блоку, а не input, селекторов по тегу нужно избегать

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +.formGroup  {
этот элемент должен оборачивать каждое поле, а не всю форму целиком

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +    border-radius: 3px;
border-radius: 3px вместо border-radius: 3px?

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/Modal/Modal.module.scss
> +    border-radius: 6px;
border-radius: 6px вместо border-radius: 6px?

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +              <Input
formGroup оборачивает каждый инпут, для того, чтобы расставить отступы

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +    <div className={styles.wrapper}>
Возможно тут стоит объединить className из props, чтобы можно было давать класс этому компоненту, тогда не придется создавать обертки вокруг инпутов

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +  size: ["small", "large"],
defaultProps.size равен массиву? Во-первых этот props пока что не имеет никакого смысла, во-вторых тут должна быть строка

2021-09-08 09:42 UTC, ZakharovMaxim commented on components/input/Input.module.scss
> +  font-family: "Montserrat";
Montserrat это наш базовый шрифт, не нужно уго указывать отдельно

2021-09-08 14:04 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +import Spiner from "../Spinner";
typo: Spinner.
Компоненты лучше импортировать перед сервисами и картинками

2021-09-08 14:17 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +        <Basketball></Basketball>
BasketballIcon?

2021-09-08 14:17 UTC, ZakharovMaxim commented on components/input/Input.jsx
> +  errorMsg,
errorMessage вместо errorMsg

2021-09-08 15:57 UTC, ZakharovMaxim approved these changes

2021-09-08 16:16 UTC, Dimirolz commented
@artemSr пофикси конфликты, и пингани меня, что бы я смерджил.

2021-09-08 16:51 UTC, ZakharovMaxim approved these changes

2021-09-09 05:27 UTC, Dimirolz requested changes

2021-09-09 05:27 UTC, Dimirolz commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +      alert(result);
@artemSr лучше убрать alert'ы перед стейджингом, это было для дебага, верно?

2021-09-09 06:47 UTC, Dimirolz requested changes

2021-09-09 06:47 UTC, Dimirolz commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +      return <p>{result}</p>;
@artemSr не нужно возвращать ничего. Просто сделай await, если упадет, то выведи в console.warn

2021-09-09 06:47 UTC, Dimirolz commented on components/ContactUsModalContent/ContactUsModalContent.jsx
> +      return <p>{e.message}</p>;
@artemSr не нужно возвращать jsx с ошибкой. Выведи в console.warn

2021-09-09 06:59 UTC, Dimirolz approved these changes

2021-09-09 06:59 UTC, merged