Dev 4/news section
Sportresurs/sportresurs pull request #45
Opened 2021-09-08 08:39 UTC by Andrii-25

2021-09-08 13:18 UTC, Dimirolz commented
@Andrii-25 пофикси, пожалуйста, ошибки eslint. Запусти у себя локально `npm run prepare`, что бы husky поставил pre-commit hook. И ты будешь до коммита ошибки eslint

2021-09-09 13:38 UTC, steven-tailor requested changes

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +    return randomColor;
NIT: Возможно так было б более читабельно. Иначе объявление переменной прямо перед её возвратом в большинстве случаев не целесообразно.

```suggestion
    const randomColorIndex = Math.floor(Math.random() * colorsArr.length);
    return colorsArr[randomColorIndex];
```

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +  function pickColor() {
Эту функцию лучше всего вынести в кастомный хук `useRandomColor`(например) который собственно будет возвращать нужный рандомный цвет.

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +          bibendum ligula, vel tempor arcu congue efficitur.
Этот текст должен быть проброшен пропсами от родителя

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +        <Image src={img} alt="news-card" layout="fill" />
Изображение должно быть проброшено пропсами от родителя

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +    const randomColor = colorsArr[Math.floor(Math.random() * colorsArr.length)];
NIT: В целом я думаю вместо рандомного цвета лучше использовать подход (алгоритм) `round robin`

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  transition: 0.5s;
`transition` должен быть указан в классе `.info` иначе как ты можешь заметить блок возвращается на место без применения `transition`.

2021-09-09 13:38 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  letter-spacing: 0.2px;
Если эти значения глобальны для проекта, то лучше их вынести "наверх" в `shared`

2021-09-09 13:38 UTC, steven-tailor commented on components/News/News.module.scss
> +
По стилям замечаний и вопросов много, но их есть смысл обсудить только после внедрения слайдера.

2021-09-10 06:11 UTC, Dimirolz commented on components/News/News.js
> +          <ul className={s.list}>
@steven-tailor Да, слайдер делается отдельной задачей у Богдана.

2021-09-10 10:00 UTC, steven-tailor commented on components/NewsCard/NewsCard.js
> +    const randomColor = colorsArr[Math.floor(Math.random() * colorsArr.length)];
Иначе достаточно часто будет вот такая картина:
![image](https://user-images.githubusercontent.com/11887651/132836881-2d8865e2-fe46-4698-8634-10dcc924ab04.png)

2021-09-14 19:51 UTC, steven-tailor requested changes

2021-09-14 19:51 UTC, steven-tailor commented on components/News/News.js
> +    imgUrl: image,
image будет undefined. @Dimirolz разве у вас git pre hooks не настроены? es-lint не должен был такое допустить.

2021-09-14 19:51 UTC, steven-tailor commented on components/News/News.js
> +        })}
Тут lint тоже должен ругнуться.
```suggestion
        {news.map((item) => (
          <NewsCard key={item.id} newsData={item} color={getColor()} />
        ))}
```

2021-09-14 19:51 UTC, steven-tailor commented on utils/hooks/useColorLoop.js
> +} from "../../../styles/exportColorVars.module.scss";
путь не верный
```suggestion
} from "../../styles/exportColorVars.module.scss";
```

2021-09-14 19:51 UTC, steven-tailor commented on components/News/News.js
> +    imgUrl: image,
@Andrii-25 перед тем как открывать PR и запрашивать review обязательно убедись что работа выполнена и протестируй. У тебя по идее проект даже запуститься не должен.

2021-09-15 06:09 UTC, Dimirolz commented on components/News/News.js
> +    imgUrl: image,
@steven-tailor husky теперь сам не устанавливает хуки автоматически. Нужно `npm run prepare` запустить, я об этом писал Андрею, должно у него работать.

2021-09-16 11:31 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  float: left;
@Andrii-25 Для чего тут использован `float` ?

2021-09-16 11:31 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  margin: -50px 10px 10px 10px;
@Andrii-25  Для чего использован `margin` ?

2021-09-16 16:19 UTC, Andrii-25 commented on components/NewsCard/NewsCard.module.scss
> +  float: left;
@steven-tailor Вже забрав.

2021-09-16 16:21 UTC, Andrii-25 commented on components/NewsCard/NewsCard.module.scss
> +  margin: -50px 10px 10px 10px;
![Знімок екрана (19)](https://user-images.githubusercontent.com/66208186/133648845-714efe32-c2a0-4ff0-8a26-3c414c1d6d20.png)
Без margin така ситуація.

2021-09-17 07:30 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  margin: -50px 10px 10px 10px;
@Andrii-25 Соррі мав на увазі навіщо -50px?

2021-09-17 07:37 UTC, steven-tailor commented on utils/hooks/useColorLoop.js
> +  return useCallback(() => colors.next().value, []);
В deps нужно указать `colors` так как ты его используешь внутри хука useCallback. в 99% случаев нужно указывать все зависимости хука.

Рекомендую прочитать на досуге: 
- https://ru.reactjs.org/docs/hooks-reference.html
- https://betterprogramming.pub/stop-lying-to-react-about-missing-dependencies-10612e9aeeda

2021-09-17 12:41 UTC, steven-tailor commented on components/NewsCard/NewsCard.module.scss
> +  float: left;
@Andrii-25 Те що я питаюсь то не обов'язково означає що ти допустив помилку. Але мені важливо розуміти чи можеш ти обґрунтувати свою реалізацію.

2021-09-21 09:17 UTC, Dimirolz commented
@steven-tailor можешь сделать ревью, как будешь свободен? 

Эту задачку ждет Артем, для того что бы добавить удаление новостей. И Богдану пригодилась бы для слайдера.

2021-09-21 17:17 UTC, steven-tailor approved these changes

2021-09-21 19:27 UTC, merged