ticket #66 - add multi select component
Sportresurs/sportresurs pull request #47
Opened 2021-09-08 13:03 UTC by Dr-Frame

2021-09-08 13:28 UTC, Dimirolz commented on components/checkbox/Checkbox.module.scss
> +    background-image: url("../../public/checked.png");
@Dr-Frame может можно как то svgr починить? Что бы можно было нормально svg использовать в background-image?

2021-09-08 13:34 UTC, Dr-Frame commented on components/checkbox/Checkbox.module.scss
> +    background-image: url("../../public/checked.png");
я вчера пару часов сидел ломал голову, фикс который предлагали не работал. Не думаю что тут очень критично 1кб вес галочки

2021-09-08 13:45 UTC, Dimirolz commented on components/checkbox/Checkbox.module.scss
> +    background-image: url("../../public/checked.png");
@Dr-Frame ты вот это пробовал? https://github.com/gregberge/svgr/issues/396

2021-09-08 14:48 UTC, Dimirolz commented on components/checkbox/Checkbox.module.scss
> +    background-image: url("../../public/checked.png");
@Dr-Frame вроде бы разобрался, нужно было issuer задать для правила с svgr, что бы svgr обрабатывал только js, jsx файлы. Могу сюда закоммитить?

2021-09-09 08:20 UTC, WebTarantul requested changes

2021-09-09 08:20 UTC, WebTarantul commented on components/checkbox/Checkbox.module.scss
>  .checkbox-label-chacked {
@Dimirolz this is the wrong way to handle component state. Please use classnames library to add state css classes. e.g. classnames('checkbox-label', {checked: isSelected})

2021-09-10 06:15 UTC, Dimirolz commented on components/checkbox/Checkbox.module.scss
>  .checkbox-label-chacked {
@xaarxus if I'm not wrong, this is your component. Can you fix it, like Taras said? Open new trello ticket, and send it as a new pull request.

2021-09-15 05:49 UTC, WebTarantul approved these changes

2021-09-15 06:03 UTC, Dimirolz commented
@Dr-Frame fix conflicts here, pls

2021-09-15 07:56 UTC, merged