code style conventions 63
Sportresurs/sportresurs pull request #48
Opened 2021-09-08 13:14 UTC by Dimirolz

2021-09-08 14:04 UTC, IgVol requested changes
please change commit and branch naming convention

Commits:
T-ticket_number Description, where description starts with capital letter verb.
f.e:
T-69 Add comments to pull request

Branches:
we aren't following gitflow in any way, so we can skip using feature/ prefixes in branches, and instead write like
t-69-add-comments-to-pull-request
We use dash without uppercase.

Pull requests should be named same as task title in Trello starting with task number.
F.e.
T-69 Review pull requests

Please note, we always use Present Simple. F.e use "Add" instead of "added". We do not use # symbol when referencing tickets, because GitHub references it like link to PR.

please make sure everybody starts following naming conventions.

Please make sure we using either .js or .jsx files exclusively.

We store images in /public folder with possible exception of svg react files.

2021-09-14 06:57 UTC, Dimirolz commented on README.md
> +5. We do not shrink the names of imports. Examples: "styles", not "s". "classNames", not "cn", etc...
@IgVol 
Questions: 
1. Do we really need to name commits with task numbers? They are inside branch with task number, already.
2. "Please make sure we usу either .js or .jsx files exclusively." - we need somehow change this rule. We have api routes, utils. They are always be .js

2021-09-14 09:20 UTC, IgVol commented on README.md
> +5. We do not shrink the names of imports. Examples: "styles", not "s". "classNames", not "cn", etc...
1. Yes. 
2. I wan't clear enough: I meant using .js or .jsx for react components. I'd always use .js

2021-09-14 09:23 UTC, Dimirolz commented on README.md
> +5. We do not shrink the names of imports. Examples: "styles", not "s". "classNames", not "cn", etc...
@IgVol 
1. I cannot understand the reason. Can you explain it to me?
2. Why not .jsx? I guess for files with jsx usage is more convinient using .jsx filetype

2021-09-14 13:52 UTC, IgVol approved these changes

2021-09-14 15:39 UTC, ZakharovMaxim approved these changes

2021-09-14 15:39 UTC, merged