finalize layout
Sportresurs/sportresurs pull request #58
Opened 2021-09-09 15:42 UTC by artemSr

2021-09-09 17:02 UTC, ZakharovMaxim requested changes

2021-09-09 17:02 UTC, ZakharovMaxim commented on pages/playgrounds.js
> +      <div id="portal" />
Это нужно вынести в общее для всех страниц место, чтобы не дублировать, можно использовать _app.js, или создать _document.js, как в статье, которую я скидывал

2021-09-10 07:11 UTC, ZakharovMaxim approved these changes

2021-09-10 07:12 UTC, Dimirolz approved these changes

2021-09-10 07:12 UTC, merged