fix validation and contact_us_modal styles
Sportresurs/sportresurs pull request #63
Opened 2021-09-10 11:12 UTC by artemSr

2021-09-10 11:18 UTC, ZakharovMaxim requested changes

2021-09-10 11:18 UTC, ZakharovMaxim commented on components/ContactUsModalContent/ContactUsModalContent.module.scss
> +  overflow: scroll;
Скролл тут не нужен, у базовой модалки уже есть overflow: auto

2021-09-10 11:27 UTC, ZakharovMaxim approved these changes

2021-09-13 06:38 UTC, ZakharovMaxim approved these changes

2021-09-13 07:11 UTC, Dimirolz approved these changes

2021-09-13 07:11 UTC, merged