T-67 implement migrations for playground functions
Sportresurs/sportresurs pull request #68
Opened 2021-09-15 15:13 UTC by Andrii-25

2021-09-15 15:42 UTC, Dimirolz requested changes

2021-09-15 15:42 UTC, Dimirolz commented on migrations/20210915141639-create-purpose.js
> +        type: Sequelize.ARRAY(Sequelize.STRING),
@Andrii-25 не совсем то что нам нужно. Лучше сделать каждую строку в базе отдельным Purpose.
То есть у purpose есть id, title, created_at и updated_at

2021-09-15 15:42 UTC, Dimirolz commented on migrations/20210915141639-create-purpose.js
> +      createdAt: {
Для консистентности лучше использовать именование полей через underscore. created_at

2021-09-15 15:42 UTC, Dimirolz commented on models/purpose-area.js
> +      modelName: "PurposeArea",
@Andrii-25 ты проверял? это работает? Я не совсем понимаю как оно сматчит класс и таблицу

2021-09-15 15:42 UTC, Dimirolz commented on models/purpose.js
> +      modelName: "Purpose",
@Andrii-25 нужно думаю добавить `undersored: true` ко всем моделям. Что бы оно само использовало `created_at`, который мы в миграции сделаем через underscore

2021-09-15 15:42 UTC, Dimirolz commented on migrations/20210915143115-create-purpose-area.js
> +      createdAt: {
@Andrii-25 тут тоже самое, с underscore. Я так просто уже начал в других таблицах именовать

2021-09-16 07:34 UTC, Dimirolz commented on migrations/20210915141639-create-purpose.js
> +        type: Sequelize.STRING,
@Andrii-25 можно добавить `allowNull: false`, мы вряд ли разрешим создавать назначения без названий.

2021-09-16 09:35 UTC, Dimirolz commented on models/purpose-area.js
> +  PurposeArea.init(
@Andrii-25 можешь посмотреть как создавать отношения между таблицами? В нашем случае у нас есть many-to-many между Площадками и Назначениями.

2021-09-17 06:46 UTC, Dimirolz commented
@steven-tailor можешь посмотреть? По моим правкам все сделано

2021-09-17 12:38 UTC, epaminond commented
Мне выглядит норм, но мне бросается в глаза:

1. Не ясно, для чего операция разбита на несколько миграций. В идеале миграция переводит базу из одного консистентного состояния в другое. А с таким подходом может оказаться, что у нас отранилась только часть миграций (например есть таблица Purposes, но остался ENUM).
2. Если прогнать эти миграции, то похоже, что существующие данные поломаются: ENUM удалится, а связи не создадутся. Это неожиданно и это тяжело мигрировать, например в проде. Я бы предложил все данные также мигрировать: засидить и создать связи

2021-09-20 08:33 UTC, Dimirolz commented
@epaminond данных на данный момент в базе нет, так что пока ничего не сломается. Сами данные для сидинга я в отдельной задаче готовлю и там я уже засижу с ассоциациями, с учетом этих миграций.

2021-09-20 09:43 UTC, epaminond commented
Ну тогда объединить бы миграции в одну хотя бы.
Я бы говорил в любом случае позаботится о данных - это хорошая практика и хороший пример для будущих миграций был бы. Иначе выходит, что миграция может повести себя непредсказуемо в каких-то ситуациях.

2021-09-20 18:09 UTC, Dimirolz commented
@epaminond а как выглядит "позаботиться о данных" на практике в данном случае? Не совсем этот момент понимаю. Как можно что то засидить и добавить ассоциации, если в базе еще нет данных?

2021-09-21 07:09 UTC, epaminond commented
@Dimirolz , например так:

- создать таблицы purpose и purpose-area
- заполнить таблицу purpose идентично ENUMу в таблице areas (кстати, я бы всё же использовал латинские названия-коды аля football вместо футбол и переводил их по надобности - но то такое)
- достать кверёй все areas
- для каждой area создать purpose-area на основе значения из ENUM (если данных в базе нет, то кверя не вернёт результатов и та часть миграции скипнется просто)
- удалить колонку purpose из areas

Ну и в "down" проделать обратную операцию.

При таком подходе эту миграцию безопасно проганять всегда и везде, независимо есть ли там данные у кого-то или нет.
В большой команди с несколькими environment'ами - это на много легче, чем бегать по кругу между девелоперами и девопсом, когда у каждого что-то падает в какой-то миграции или отваливается после неё.

2021-09-21 09:16 UTC, Dimirolz commented
@epaminond Теперь у меня пазл в голове сложился, спасибо :)

В данном конкретном случае как поступим с этим знанием?
Мне кажется это полезно Андрею тоже понять, но применить в другой раз, мы не будем уже откатываться к тому состоянию, в котором были enum.

2021-09-21 09:57 UTC, epaminond commented
На твоё усмотрение. )

2021-09-21 10:36 UTC, Dimirolz approved these changes

2021-09-22 06:23 UTC, steven-tailor approved these changes

2021-09-22 06:51 UTC, merged