T 89 implement opening modal
Sportresurs/sportresurs pull request #73
Opened 2021-09-20 06:56 UTC by Andrii-25

2021-09-23 16:22 UTC, Dimirolz commented
@steven-tailor сделай ревью, как будет время

2021-09-23 19:41 UTC, steven-tailor requested changes

2021-09-23 19:41 UTC, steven-tailor commented on components/CourtCard/CourtCard.js
> +  const [modal, setModal] = useState(false);
NIT: лучше указать более понятное название вроде `isModalShow` или `isModalOpened`. Как правило, суффикс `is` говорит о том что переменная хранит булевское значение.

2021-09-23 19:41 UTC, steven-tailor commented on components/PlaygroundItem/PlaygroundItem.jsx
> +  const [modal, setModal] = useState(false);
Так как в проекте часто используются модальные окна лучше создать кастомных хук типа:
`const [isModalShown, handleOpenModal, handleCloseModal] = useModalHandlers();`

2021-09-23 19:41 UTC, steven-tailor commented on components/PlaygroundItem/PlaygroundItem.jsx
> +          modal={handleOpen}
Это кажется не явным действием. Prop носит название сущности `modal`, а принимает `handler` открывания модалки.

2021-09-27 20:22 UTC, steven-tailor approved these changes

2021-09-28 14:22 UTC, Dimirolz submitted a review, later dismissed

2021-09-28 14:23 UTC, Dimirolz commented
@Andrii-25 пофикси конфликты, что бы я смог смерджить

2021-09-29 16:45 UTC, Dimirolz approved these changes

2021-09-29 16:45 UTC, merged