wip: t-18 expand thanks modal component
Sportresurs/sportresurs pull request #76
Opened 2021-09-20 17:23 UTC by artemSr

2021-09-20 18:02 UTC, ZakharovMaxim requested changes

2021-09-20 18:02 UTC, ZakharovMaxim commented on components/SuccessDialog/SuccessDialog.jsx
> +    onClose={onClose}
Лучше переместить в конец списка

2021-09-20 18:02 UTC, ZakharovMaxim commented on components/Dialog/Dialog.jsx
> +  header,
Лучше назвать title

2021-09-20 18:02 UTC, ZakharovMaxim commented on components/Dialog/Dialog.jsx
> +  isAdmin = false,
Нужно заменить этот prop и сделать компонент более универсальным

2021-09-22 10:03 UTC, ZakharovMaxim requested changes

2021-09-22 10:03 UTC, ZakharovMaxim commented on components/NewsCard/NewsCard.js
> +export default function NewsCard({ newsData, color, canRemove, onOpen }) {
Не совсем понимаю onOpen, выглядит как-будто новость можно открыть. Лучше подойдет, например, onDeleteIconClick.
Второй момент, лучше заменить canRemove на canDelete, так как бы везде используем слово delete, чтобы не возникала путаницу из-за этого

2021-09-22 10:03 UTC, ZakharovMaxim commented on components/SuccessDialog/SuccessDialog.jsx
> +const SuccessDialog = ({ isShow, shouldLockScreen, onClose }) => (
isShow, тогда как другие диалоги и модалки принимают visible

2021-09-22 11:53 UTC, ZakharovMaxim approved these changes

2021-09-22 11:55 UTC, Dimirolz approved these changes

2021-09-22 11:55 UTC, merged