T-109 On header highlight current page link + add anchors
Sportresurs/sportresurs pull request #79
Opened 2021-09-21 07:18 UTC by Bohdan-R

2021-09-22 09:20 UTC, IgVol requested changes

2021-09-22 09:20 UTC, IgVol commented on components/About/About.js
> +  const heightOfHeader = useMemo(() => setHeightOfHeader(size.width), [size]);
Why we find height of header using javascript and not using css?

2021-09-22 09:20 UTC, IgVol commented on utils/findHeightOfHeader.js
> +  if (windowSize >= 1024) {
is there any specific reasoning behind selecting this values for windowSize?

2021-09-28 14:39 UTC, WebTarantul requested changes

2021-09-28 14:39 UTC, WebTarantul commented on components/About/About.js
> +import ScrollableAnchor, { configureAnchors } from "react-scrollable-anchor";
![image](https://user-images.githubusercontent.com/34688235/135107019-1febfe3a-5655-4625-b908-461880a3bb2b.png)

2021-09-28 14:39 UTC, WebTarantul commented on components/About/About.js
> +import ScrollableAnchor, { configureAnchors } from "react-scrollable-anchor";
Navigation does't work.
You can fix it or you can use combination css property  scroll-behavior: smooth; and js functions: scroll or scrollIntoView INSTEAD react scrollable anchor library

2021-09-30 13:20 UTC, IgVol requested changes
Looks ok to me, keep codebase clean though

2021-09-30 13:20 UTC, IgVol commented on components/About/About.module.scss
> +/* #navigateToAboutUs {
delete commented code

2021-09-30 16:41 UTC, WebTarantul requested changes
To implement correct behavior you need write some function to handle scrolling according params in the history. Then use it at click on the link in the header.
If it's possible to use position sticky for header instead fixed, you can use element.scrollIntoView function and additioanally you don't need use setHeigthOfHeader funciton and it's greate.
 If it is't possible(use position sticky) then you can use scrollTo function, but with correct options.

2021-09-30 16:41 UTC, WebTarantul commented on components/Header/Header.js
> +                  <Link href="/#navigateToAboutUs">
As a developer you want prevent default behavior and use your own function. At the moment default behavior conflicts with your useEffect in a some components.

2021-10-06 09:11 UTC, WebTarantul requested changes

2021-10-06 09:11 UTC, WebTarantul commented on components/Header/Header.js
> +/* eslint-disable jsx-a11y/no-static-element-interactions */
Don't use opportunity like this. Please remove this disable comment and fix any issues according to that rule.

2021-10-06 09:11 UTC, WebTarantul commented on components/About/About.module.scss
> +/* #navigateToAboutUs {
Please, delete commented code

2021-10-06 09:40 UTC, WebTarantul approved these changes

2021-10-06 10:31 UTC, Dimirolz approved these changes

2021-10-06 10:32 UTC, merged