T-2 Create search section on home page
Sportresurs/sportresurs pull request #80
Opened 2021-09-21 07:32 UTC by Bohdan-R

На страницу площадок (для тестирования) через контекст передаю координаты улицы в поиске, после апрува все лишнее уберу.

2021-09-22 09:16 UTC, IgVol requested changes

2021-09-22 09:16 UTC, IgVol commented on components/SearchSection/SearchSection.js
> +    const ll = await getLatLng(result[0]);
please use full names for variables or comment code, so its easier for understand whats going on

2021-09-22 09:16 UTC, IgVol commented on components/SearchSection/SearchSection.js
> +    if (typeof window !== "undefined") {
typeof window !== "undefined" is a check, which used by some libraries to know if they run in browser or not

you might want to check if we have window.google loaded 
something like this 
const searchOptions = () => window.google && {
        location: new window.google.maps.LatLng(49.842957, 24.031111),
        radius: 30000,
        types: ["address"],
      }

2021-09-22 09:33 UTC, Dimirolz commented
@Bohdan-R как будет обновление страницы, при передаче через контекст? При обновлении страницы поиск пропадет? Если так, то мы вроде бы обсуждали вариант с передачей через query параметры

2021-09-27 13:09 UTC, IgVol approved these changes

2021-09-27 13:47 UTC, Dimirolz commented
@Bohdan-R пофикси конфликты, что я мог мерджить

2021-09-28 05:59 UTC, Dimirolz approved these changes

2021-09-28 05:59 UTC, merged