T-108 Update map pins
Sportresurs/sportresurs pull request #83
Opened 2021-09-21 12:04 UTC by Bohdan-R

2021-09-22 08:54 UTC, IgVol requested changes

2021-09-22 08:54 UTC, IgVol commented on components/Marker/Marker.js
> +        <svg
Please use svg as an import

2021-09-22 08:54 UTC, IgVol commented on components/Marker/Marker.js
> +        {typeOfCourt === "BasketballCourt" && (
Create an object outside component like this 
```
const courtImages = {
  typeOfCourt: CourtImage, 
}
```
And then change the code to something like:
```
<div className={styles.icon}>
    <Image src={courtImages[typeOfCourt]} alt={typeOfCourt} />
  </div>
```

2021-09-28 15:03 UTC, WebTarantul requested changes
https://github.com/Sportresurs/sportresurs/pull/83#discussion_r717586914
Why did you remove courtImages object?

2021-09-29 16:44 UTC, Dimirolz commented
@IgVol @WebTarantul правки выполнены, дайте ваше ревью, как у вас будет получаться

2021-09-30 13:26 UTC, IgVol requested changes
Right nowwe have markers as .png files, is there any chance we can use .svg?

2021-09-30 13:26 UTC, IgVol commented on components/Marker/Marker.js
> +              red: district === "Halytskyi",
please use the following logic

```
const districtToColor = {
  Halitskyi: 'red',
  ...
}

<MapMarker className={districtToColor[district]}
```

2021-10-01 08:18 UTC, IgVol approved these changes

2021-10-01 08:19 UTC, Dimirolz commented
@Bohdan-R исправь конфликты, что бы я смог смерджить

2021-10-01 09:08 UTC, Dimirolz approved these changes

2021-10-01 09:09 UTC, merged