T-23 Ability to register others admins UI
Sportresurs/sportresurs pull request #85
Opened 2021-09-22 15:54 UTC by Andrii-25

2021-09-22 15:56 UTC, Andrii-25 commented
Додав валідацію через formik і в мене там помилка при спробі додати або редагувати адміна, і я не розумію чому.

2021-09-22 16:00 UTC, Dimirolz commented
@Andrii-25 исправь ошибку eslint. Нужно смерджиться с develop. Там есть необходимые файлы.

2021-09-23 16:24 UTC, Dimirolz commented
@steven-tailor сделай ревью, как будет время

2021-09-23 19:57 UTC, steven-tailor requested changes

2021-09-23 19:57 UTC, steven-tailor commented on components/AdminList/AdminList.js
> +  const DELETED = "deleted";
В таких случаях можно создать подобие типа `enum`
```suggestion
const eAdminStatus = {
  LOGGED: 'logged',
  NOTLOGGED: 'notLoggedIn',
  DELETED: 'deleted',
}
```

2021-09-23 19:57 UTC, steven-tailor commented on components/AdminList/AdminList.js
> +    return null;
Таки условные блоки можно заменять подобным образом:
```suggestion
    switch(status) {
      case status === eAdminStatus.LOGGED:
        return <Tick className={s.icon} />;
        
      ...
      
      default:
        return null;
    }
   
```

2021-09-23 19:57 UTC, steven-tailor commented on components/AdminList/AdminList.js
> +  function handleChange(e) {
Рекомендую ознакомиться с [документацией](https://ru.reactjs.org/docs/hooks-reference.html#usecallback) и [статьей](https://aheadcreative.co.uk/articles/when-to-use-react-usecallback/). После чего, возможно исправить некоторые функции с использованием `useCallback` хука.

2021-09-27 20:10 UTC, steven-tailor approved these changes

2021-09-28 14:20 UTC, Dimirolz approved these changes

2021-09-28 14:20 UTC, merged