t-117-implement-error-pages
Sportresurs/sportresurs pull request #90
Opened 2021-09-24 07:34 UTC by Dr-Frame

2021-09-27 06:25 UTC, Dimirolz commented
@Dr-Frame можешь добавить в сам next 404 страницу?
Почитать можно вот тут. https://nextjs.org/docs/advanced-features/custom-error-page
Ее путь должен быть pages/404.js

И попробуй добавить страницу ошибки. Она сейчас задается в _app.js как fallback у Sentry.withErrorBoundary.

2021-09-27 07:46 UTC, WebTarantul requested changes

2021-09-27 07:46 UTC, WebTarantul commented on pages/error/Error.module.scss
> +  @media screen and (min-width: 320px) and (max-width: 425px) {
You can use only min or max query.

2021-09-28 10:15 UTC, WebTarantul approved these changes

2021-09-28 14:18 UTC, Dimirolz commented
@Dr-Frame пофикси конфликт, что бы я смог смерджить

2021-09-29 16:44 UTC, Dimirolz approved these changes

2021-09-29 16:44 UTC, merged