T-92 Аdd slider to the modal playgrounds details
Sportresurs/sportresurs pull request #96
Opened 2021-09-28 06:46 UTC by Bohdan-R

2021-09-28 13:19 UTC, WebTarantul requested changes

2021-09-28 13:19 UTC, WebTarantul commented on components/PlaygroundModalContent/PlaygroundModalContent.jsx
> +          isArrows={true}
I think 'withArrows' is more clear name.

2021-09-28 13:19 UTC, WebTarantul commented on components/PlaygroundModalContent/PlaygroundModalContent.jsx
> +            <>
Is no reason to use Fragment here

2021-09-28 13:19 UTC, WebTarantul commented on components/PlaygroundModalContent/PlaygroundModalContent.module.scss
> +.sliderBox .dots.modalDots {
Here is no reason to use too many css classes. You need as many classes as you need to redefine styles.

2021-09-28 13:19 UTC, WebTarantul commented on components/PlaygroundModalContent/PlaygroundModalContent.module.scss
> +.sliderBox .dots.modalDots ul {
Here is no reason to use too many css classes. You need as many classes as you need to redefine styles.


Plese change all lines according that tip

2021-09-28 13:19 UTC, WebTarantul commented on components/Slider/Slider.js
>    classNameArrow,
I think you don't need too many props for css class. You can use one class for wrapper element and then use other exists classes of inside elements

2021-09-29 16:43 UTC, Dimirolz commented
@WebTarantul @IgVol дайте ваше ревью, как будет время, Богдан сделал необходимые фиксы

2021-09-30 17:25 UTC, Dimirolz commented
@Bohdan-R пофикси конфликты, что бы я смог смерджить

2021-10-01 09:11 UTC, Dimirolz approved these changes

2021-10-01 09:11 UTC, merged